const SUPABASE_URL="https://pzaiwbsikhmnfnlrvtld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_d2ghHV2agZ0xV0tr3GL1iQ_Gqbk50D6";
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const app=document.getElementById("app"),authModal=document.getElementById("authModal"),listingModal=document.getElementById("listingModal"),toast=document.getElementById("toast");let currentUser=null,currentListings=[],authMode="login",currentFilter="all";
const cats=[["Elektronik","barang","elektronik"],["Furniture","barang","furniture"],["Buku & Kuliah","barang","buku-perlengkapan-kuliah"],["Pakaian","barang","pakaian"],["Motor","barang","motor"],["Design","jasa","design"],["Video Editing","jasa","video-editing"],["Les Privat","jasa","les-privat"],["Pengetikan","jasa","pengetikan-dokumen"]];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v||0);
function toastMsg(m){toast.textContent=m;toast.classList.add("show");clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove("show"),2500)}
function skeletons(n){return Array.from({length:n},()=>'<div class="skeleton"></div>').join("")}
function setMode(m){authMode=m;const r=m==="register";document.getElementById("authTitle").textContent=r?"Buat akun":"Masuk";document.getElementById("authSubmit").textContent=r?"Daftar":"Masuk";document.querySelectorAll(".register-only").forEach(x=>x.classList.toggle("hidden",!r));document.getElementById("name").required=r;document.getElementById("loginTab").classList.toggle("active",!r);document.getElementById("registerTab").classList.toggle("active",r)}
function openAuth(m="login"){authModal.classList.remove("hidden");setMode(m)}function closeAuth(){authModal.classList.add("hidden")}
async function loadUser(){const{data}=await supabase.auth.getUser();currentUser=data.user||null;updateAccount()}
async function updateAccount(){const b=document.getElementById("accountBtn");if(!currentUser){b.textContent="Masuk";return}const{data:p}=await supabase.from("profiles").select("name").eq("id",currentUser.id).maybeSingle();b.textContent=p?.name?.split(" ")[0]||"Akun"}
async function submitAuth(e){e.preventDefault();const msg=document.getElementById("authMessage");msg.textContent="";const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,name=document.getElementById("name").value.trim(),whatsapp=document.getElementById("whatsapp").value.trim();try{let r;if(authMode==="register")r=await supabase.auth.signUp({email,password,options:{data:{name,whatsapp:whatsapp||null}}});else r=await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;currentUser=r.data.user;msg.textContent=authMode==="register"&&!r.data.session?"Akun dibuat. Cek email konfirmasi.":"Berhasil.";msg.className="form-message success";if(r.data.session){closeAuth();updateAccount();route()}}catch(x){msg.textContent=x.message||"Terjadi kesalahan.";msg.className="form-message error"}}
async function logout(){await supabase.auth.signOut();currentUser=null;updateAccount();location.hash="#home";toastMsg("Kamu sudah keluar.")}
function home(){return '<section class="page"><section class="hero"><p class="eyebrow">MARKETPLACE LOKAL</p><h1>Cari barang & jasa di sekitar Padangsidimpuan.</h1><p>Temukan barang bekas, kebutuhan mahasiswa, dan jasa dari orang sekitar.</p><form class="search-wrap" id="homeSearch"><input id="homeQuery" placeholder="Cari laptop, meja kos, desain logo..."><button class="btn primary">Cari</button></form></section><section class="section"><div class="section-head"><h2>Kategori populer</h2><a href="#browse">Lihat semua</a></div><div class="category-row">'+cats.slice(0,6).map(c=>'<button class="category-chip" data-category="'+c[2]+'">'+esc(c[0])+'<span>'+esc(c[1])+'</span></button>').join("")+'</div></section><section class="section"><div class="section-head"><h2>Listing terbaru</h2><a href="#browse">Jelajah</a></div><div id="homeListings" class="listing-grid">'+skeletons(4)+'</div></section><section class="section trust"><strong>Transaksi tetap di tangan kamu.</strong><p>Periksa barang dan sepakati pembayaran sebelum transaksi.</p></section><section class="section empty"><h2>Punya barang atau jasa?</h2><p>Pasang listing dan tunggu moderasi admin.</p><button class="btn primary" id="heroSell">＋ Jual barang / jasa</button></section></section>'}
function browse(){return '<section class="page"><div class="page-title"><p class="eyebrow">JELAJAH</p><h1>Temukan listing</h1><p class="muted">Cari barang dan jasa yang tersedia.</p></div><form class="search-wrap" id="browseSearch"><input id="browseQuery" placeholder="Cari barang atau jasa..."><button class="btn primary">Cari</button></form><div class="browse-toolbar"><button class="filter-chip active" data-filter="all">Semua</button><button class="filter-chip" data-filter="barang">Barang</button><button class="filter-chip" data-filter="jasa">Jasa</button>'+cats.map(c=>'<button class="filter-chip" data-filter="'+c[2]+'">'+esc(c[0])+'</button>').join("")+'</div><div id="browseListings" class="listing-grid">'+skeletons(6)+'</div></section>'}
function account(){if(!currentUser)return '<section class="page"><div class="page-title"><p class="eyebrow">AKUN</p><h1>Masuk untuk mengelola akun</h1><p class="muted">Kelola listing, favorit, dan profilmu.</p><button class="btn primary" id="accountLogin">Masuk / Daftar</button></div></section>';return '<section class="page"><div class="page-title"><p class="eyebrow">AKUN</p><h1>Akun kamu</h1><p class="muted">'+esc(currentUser.email)+'</p></div><div class="section empty"><h2>Listing Saya</h2><p>Aktif, pending, terjual, ditolak, dan diarsipkan akan masuk di modul Seller.</p><button class="btn primary" id="accountSell">＋ Buat listing</button></div><div class="section empty"><h2>Favorit</h2><p>Favorit akan tersimpan di database akunmu.</p></div><button class="btn secondary full" id="accountLogout">Keluar</button></section>'}
function favorites(){return '<section class="page"><div class="page-title"><p class="eyebrow">FAVORIT</p><h1>Listing yang kamu simpan.</h1></div><div class="empty">Belum ada favorit.</div></section>'}
function sell(){if(!currentUser){openAuth();return account()}return '<section class="page"><div class="page-title"><p class="eyebrow">JUAL</p><h1>Pasang listing</h1><p class="muted">Pilih barang atau jasa. Form lengkap masuk pada tahap Seller.</p></div><div class="category-row"><button class="category-chip" id="sellGoods">▣ Barang<span>Elektronik, furniture, buku, pakaian, motor.</span></button><button class="category-chip" id="sellService">✦ Jasa<span>Design, editing, les, dokumen, terjemahan.</span></button></div></section>'}
async function getListings(f){let q=supabase.from("listings").select("id,title,description,type,status,contact_whatsapp,created_at,item_details(price,condition,cod_location),service_details(price_text,work_mode),listing_images(storage_path,sort_order),profiles(name,whatsapp),categories(name,slug)").eq("status","published").order("created_at",{ascending:false}).limit(24);if(f.type)q=q.eq("type",f.type);if(f.category)q=q.eq("categories.slug",f.category);if(f.q){const s=f.q.replace(/[,%]/g," ").trim();if(s)q=q.or("title.ilike.%"+s+"%,description.ilike.%"+s+"%")}return q}
function card(x){const d=x.type==="barang"?x.item_details?.[0]:x.service_details?.[0],im=(x.listing_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0],url=im?.storage_path?supabase.storage.from("listing-images").getPublicUrl(im.storage_path).data.publicUrl:null,p=x.type==="barang"?(d?.price!=null?money(d.price):"Harga belum diisi"):(d?.price_text||"Harga sesuai layanan");return '<article class="listing-card" data-id="'+x.id+'"><div class="listing-media">'+(url?'<img src="'+esc(url)+'" alt="'+esc(x.title)+'" loading="lazy">':"<span>Foto belum tersedia</span>")+'</div><div class="listing-body"><div class="listing-title">'+esc(x.title)+'</div><div class="price">'+esc(p)+'</div><div class="meta">'+esc(x.categories?.name||"Lainnya")+' · '+esc(d?.condition||"Jasa")+'</div><div class="meta">📍 '+esc(d?.cod_location||"Padangsidimpuan")+'</div></div></article>'}
async function render(id,f){const el=document.getElementById(id);if(!el)return;el.innerHTML=skeletons(id==="homeListings"?4:6);const{data,error}=await getListings(f);if(error){el.innerHTML='<div class="error-box">Gagal memuat listing.</div>';return}currentListings=data||[];el.innerHTML=currentListings.length?currentListings.map(card).join(""):'<div class="empty">Belum ada listing aktif. Nanti barang dan jasa akan muncul di sini.</div>';el.querySelectorAll("[data-id]").forEach(c=>c.addEventListener("click",()=>detail(c.dataset.id)))}
async function detail(id){const x=currentListings.find(v=>v.id===id);if(!x)return;const d=x.type==="barang"?x.item_details?.[0]:x.service_details?.[0],im=(x.listing_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0],url=im?.storage_path?supabase.storage.from("listing-images").getPublicUrl(im.storage_path).data.publicUrl:null,n=(x.contact_whatsapp||x.profiles?.whatsapp||"").replace(/\D/g,"").replace(/^0/,"62");document.getElementById("listingDetail").innerHTML='<p class="eyebrow">'+esc(x.categories?.name||"Listing")+'</p><div class="detail-media">'+(url?'<img src="'+esc(url)+'" alt="'+esc(x.title)+'">':"Foto belum tersedia")+'</div><h2>'+esc(x.title)+'</h2><div class="detail-price">'+esc(x.type==="barang"?(d?.price!=null?money(d.price):"Harga belum diisi"):(d?.price_text||"Harga sesuai layanan"))+'</div><p class="muted">📍 '+esc(d?.cod_location||"Padangsidimpuan")+'</p><div class="detail-section"><strong>Deskripsi</strong><p>'+esc(x.description||"Belum ada deskripsi.")+'</p></div><div class="detail-section"><strong>Penjual</strong><div class="seller-box">'+esc(x.profiles?.name||"Penjual")+'</div></div><div class="detail-section trust"><strong>Tips aman</strong><p>Periksa barang sebelum membayar. Jangan berikan OTP atau data sensitif.</p></div>'+(n?'<a class="btn primary full sticky-cta" target="_blank" rel="noopener" href="https://wa.me/'+n+'?text='+encodeURIComponent("Halo, saya melihat listing \""+x.title+"\" di Lapak Sidimpuan.")+'">💬 Hubungi via WhatsApp</a>':"");listingModal.classList.remove("hidden")}
function nav(r){document.querySelectorAll("[data-nav]").forEach(a=>a.classList.toggle("active",a.dataset.nav===r))}
function route(){const r=(location.hash.replace(/^#/,"")||"home").split("/")[0];if(r==="home"){app.innerHTML=home();nav("home");render("homeListings",{});bindHome()}else if(r==="browse"){app.innerHTML=browse();nav("browse");bindBrowse();loadBrowse()}else if(r==="account"){app.innerHTML=account();nav("account");bindAccount()}else if(r==="favorites"){app.innerHTML=favorites();nav("favorites")}else if(r==="sell"){app.innerHTML=sell();nav("");bindSell()}else location.hash="#home"}
function bindHome(){document.getElementById("homeSearch")?.addEventListener("submit",e=>{e.preventDefault();const q=document.getElementById("homeQuery").value.trim();location.hash="#browse";setTimeout(()=>{const i=document.getElementById("browseQuery");if(i){i.value=q;document.getElementById("browseSearch").dispatchEvent(new Event("submit"))}},0)});document.querySelectorAll("[data-category]").forEach(b=>b.addEventListener("click",()=>{currentFilter=b.dataset.category;location.hash="#browse"}));document.getElementById("heroSell")?.addEventListener("click",()=>location.hash="#sell")}
function loadBrowse(){const q=document.getElementById("browseQuery")?.value||"",f=currentFilter;render("browseListings",{type:["barang","jasa"].includes(f)?f:null,category:["all","barang","jasa"].includes(f)?null:f,q})}
function bindBrowse(){document.getElementById("browseSearch")?.addEventListener("submit",e=>{e.preventDefault();loadBrowse()});document.querySelectorAll(".filter-chip").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter-chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;loadBrowse()}))}
function bindAccount(){document.getElementById("accountLogin")?.addEventListener("click",()=>openAuth());document.getElementById("accountSell")?.addEventListener("click",()=>location.hash="#sell");document.getElementById("accountLogout")?.addEventListener("click",logout)}
function bindSell(){document.getElementById("sellGoods")?.addEventListener("click",()=>toastMsg("Form barang masuk tahap Seller berikutnya."));document.getElementById("sellService")?.addEventListener("click",()=>toastMsg("Form jasa masuk tahap Seller berikutnya."))}
document.getElementById("accountBtn").addEventListener("click",()=>currentUser?location.hash="#account":openAuth());document.getElementById("headerSearchBtn").addEventListener("click",()=>location.hash="#browse");document.getElementById("sellNav").addEventListener("click",()=>location.hash="#sell");document.getElementById("closeAuth").addEventListener("click",closeAuth);document.getElementById("closeListing").addEventListener("click",()=>listingModal.classList.add("hidden"));document.getElementById("loginTab").addEventListener("click",()=>setMode("login"));document.getElementById("registerTab").addEventListener("click",()=>setMode("register"));document.getElementById("authForm").addEventListener("submit",submitAuth);document.getElementById("authModal").addEventListener("click",e=>{if(e.target===authModal)closeAuth()});document.getElementById("listingModal").addEventListener("click",e=>{if(e.target===listingModal)listingModal.classList.add("hidden")});window.addEventListener("hashchange",route);supabase.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;updateAccount()});setMode("login");loadUser().then(route);