// URL proyek Supabase. Jangan diganti kecuali kamu membuat proyek Supabase baru.
const SUPABASE_URL="https://pzaiwbsikhmnfnlrvtld.supabase.co";
// Publishable key digunakan oleh frontend; keamanan database tetap ditentukan oleh RLS Supabase.
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_d2ghHV2agZ0xV0tr3GL1iQ_Gqbk50D6";
// Client Supabase untuk Auth, Database, Storage, dan Favorites.
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const app=document.getElementById("app"),authModal=document.getElementById("authModal"),listingModal=document.getElementById("listingModal"),toast=document.getElementById("toast");
let currentUser=null,currentListings=[],authMode="login",currentFilter="all",sellerMode="barang",browsePage=0,browseHasMore=false,browseLoading=false;
const cats=[["Elektronik","barang","elektronik"],["Furniture","barang","furniture"],["Buku & Kuliah","barang","buku-perlengkapan-kuliah"],["Pakaian","barang","pakaian"],["Motor","barang","motor"],["Lainnya","barang","lainnya"],["Design","jasa","design"],["Video Editing","jasa","video-editing"],["Les Privat","jasa","les-privat"],["Pengetikan","jasa","pengetikan-dokumen"],["Terjemahan","jasa","terjemahan"],["Lainnya","jasa","lainnya"]];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v||0);
function toastMsg(m){toast.textContent=m;toast.classList.add("show");clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove("show"),2500)}
function skeletons(n){return Array.from({length:n},()=>'<div class="skeleton"></div>').join("")}
function setMode(m){authMode=m;const r=m==="register";document.getElementById("authTitle").textContent=r?"Buat akun":"Masuk";document.getElementById("authSubmit").textContent=r?"Daftar":"Masuk";document.querySelectorAll(".register-only").forEach(x=>x.classList.toggle("hidden",!r));document.getElementById("name").required=r;document.getElementById("loginTab").classList.toggle("active",!r);document.getElementById("registerTab").classList.toggle("active",r)}
function openAuth(m="login"){authModal.classList.remove("hidden");setMode(m)}function closeAuth(){authModal.classList.add("hidden")}
async function loadUser(){const{data}=await sb.auth.getUser();currentUser=data.user||null;updateAccount()}
async function updateAccount(){const b=document.getElementById("accountBtn");if(!currentUser){b.textContent="Masuk";return}const{data:p}=await sb.from("profiles").select("name").eq("id",currentUser.id).maybeSingle();b.textContent=p?.name?.split(" ")[0]||"Akun"}
async function submitAuth(e){e.preventDefault();const msg=document.getElementById("authMessage");msg.textContent="";const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,name=document.getElementById("name").value.trim(),whatsapp=document.getElementById("whatsapp").value.trim();try{const r=authMode==="register"?await sb.auth.signUp({email,password,options:{data:{name,whatsapp:whatsapp||null},emailRedirectTo:"https://8bitlanok.github.io/lapak-sidimpuan/"}}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;currentUser=r.data.user;msg.textContent=authMode==="register"&&!r.data.session?"Akun dibuat. Cek email konfirmasi.":"Berhasil.";msg.className="form-message success";if(r.data.session){closeAuth();updateAccount();route()}}catch(x){msg.textContent=x.message||"Terjadi kesalahan.";msg.className="form-message error"}}
async function logout(){try{await sb.auth.signOut()}catch(e){}currentUser=null;updateAccount();location.hash="#home";route();toastMsg("Kamu sudah keluar.")}
/* HOME: halaman depan. Visual dibuat ringan agar tidak menambah dependency. */
function home(){return `
<section class="page">
  <section class="hero">
    <p class="eyebrow">MARKETPLACE LOKAL</p>
    <h1>Cari barang & jasa di sekitar Padangsidimpuan.</h1>
    <p>Temukan barang bekas, kebutuhan mahasiswa, dan jasa dari orang sekitar.</p>
    <!-- Tiga kartu visual ini sengaja tidak memakai gambar eksternal. -->
    <div class="hero-visual">
      <div class="visual-main">
        <div class="visual-icon">🛍️</div>
        <div class="visual-copy"><strong>Barang yang masih berguna.</strong><span>Furniture kos, elektronik, buku, pakaian, motor, dan lainnya.</span></div>
      </div>
      <div class="visual-stack">
        <div class="visual-side"><div class="visual-icon">🧑‍💻</div><div><strong>Jasa lokal</strong><span>Design, editing, les, dokumen, terjemahan.</span></div></div>
        <div class="visual-side"><div class="visual-icon">📍</div><div><strong>Fokus Sidimpuan</strong><span>Lebih dekat untuk COD dan komunikasi.</span></div></div>
      </div>
    </div>
    <form class="search-wrap" id="homeSearch"><input id="homeQuery" placeholder="Cari laptop, meja kos, desain logo..."><button class="btn primary">Cari</button></form>
  </section>

  <section class="section">
    <div class="section-head"><h2>Kategori populer</h2><a href="#browse">Lihat semua</a></div>
    <div class="category-row">
      ${cats.slice(0,9).map((c,i)=>{const icons=["💻","🪑","📚","👕","🏍️","📦","🎨","🎬","📖"];return '<button class="category-chip" data-category="'+c[2]+'"><span class="category-icon">'+icons[i]+'</span>'+esc(c[0])+'<span>'+esc(c[1])+'</span></button>'}).join("")}
    </div>
  </section>

  <section class="section">
    <div class="section-head"><h2>Listing terbaru</h2><a href="#browse">Jelajah</a></div>
    <div id="homeListings" class="listing-grid">${skeletons(4)}</div>
  </section>

  <section class="section"><div class="trust"><strong>Transaksi tetap di tangan kamu.</strong><p>Lapak Sidimpuan hanya mempertemukan penjual dan pembeli. Periksa barang, sepakati tempat, dan pastikan pembayaran sebelum transaksi.</p></div></section>

  <section class="section">
    <div class="section-head"><h2>Cara kerjanya</h2></div>
    <div class="steps">
      <div class="step"><span class="step-number">1</span><strong>Temukan</strong><p>Cari barang atau jasa berdasarkan kategori dan kata kunci.</p></div>
      <div class="step"><span class="step-number">2</span><strong>Hubungi</strong><p>Buka listing lalu hubungi penjual melalui WhatsApp.</p></div>
      <div class="step"><span class="step-number">3</span><strong>Transaksi</strong><p>Atur COD atau kesepakatan langsung dengan penjual.</p></div>
    </div>
  </section>

  <section class="section empty"><h2>Punya barang atau jasa?</h2><p>Pasang listing, tunggu moderasi admin, lalu terima kontak calon pembeli.</p><button class="btn primary" id="heroSell">＋ Jual barang / jasa</button></section>
</section>`}
/* BROWSE: pencarian dan filter listing publik. */
function browse(){return '<section class="page"><div class="page-title"><p class="eyebrow">JELAJAH</p><h1>Temukan listing</h1><p class="muted">Cari barang dan jasa yang tersedia.</p></div><form class="search-wrap" id="browseSearch"><input id="browseQuery" placeholder="Cari barang atau jasa..." autocomplete="off"><button class="btn primary">Cari</button></form><div class="browse-toolbar"><button class="filter-chip active" data-filter="all">Semua</button><button class="filter-chip" data-filter="barang">Barang</button><button class="filter-chip" data-filter="jasa">Jasa</button>'+cats.map(c=>'<button class="filter-chip" data-filter="'+c[2]+'">'+esc(c[0])+'</button>').join("")+'</div><div class="browse-toolbar"><label class="muted" for="browseSort">Urutkan</label><select id="browseSort"><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select></div><div id="browseListings" class="listing-grid">'+skeletons(6)+'</div><div id="browseMore" class="browse-more"></div></section>'}
/* ACCOUNT: profil, listing milik user, dan favorit. */
function account(){if(!currentUser)return '<section class="page"><div class="page-title"><p class="eyebrow">AKUN</p><h1>Masuk untuk mengelola akun</h1><p class="muted">Kelola listing, favorit, dan profilmu.</p><button class="btn primary" id="accountLogin">Masuk / Daftar</button></div></section>';return '<section class="page"><div class="page-title"><p class="eyebrow">AKUN</p><h1>Akun kamu</h1><p class="muted">'+esc(currentUser.email)+'</p></div><div class="account-help"><div><strong>Butuh bantuan?</strong><span>Masalah akun, listing, atau transaksi.</span></div><button class="btn secondary" id="contactAdmin">Hubungi Admin</button></div><div class="account-tabs"><button class="filter-chip active" data-account-tab="listings">Listing saya</button><button class="filter-chip" data-account-tab="favorites">Favorit</button><button class="filter-chip" data-account-tab="support">Bantuan</button></div><div id="accountContent">'+skeletons(2)+'</div><button class="btn secondary full" id="accountLogout">Keluar</button></section>'}
/* FAVORITES: halaman listing yang disimpan user. */
function favorites(){return '<section class="page"><div class="page-title"><p class="eyebrow">FAVORIT</p><h1>Listing yang kamu simpan.</h1><p class="muted">Simpan barang yang belum siap kamu hubungi sekarang.</p></div><div id="favoriteListings" class="listing-grid">'+skeletons(2)+'</div></section>'}
/* SELL: form barang/jasa. Listing baru selalu masuk pending. */
function sell(){if(!currentUser){openAuth();return account()}return '<section class="page"><div class="page-title"><p class="eyebrow">SELLER</p><h1>Pasang listing</h1><p class="muted">Listing baru masuk <strong>Pending</strong> dan baru terlihat publik setelah admin menyetujuinya.</p></div><div class="seller-switch"><button class="filter-chip active" id="goodsMode">Barang</button><button class="filter-chip" id="serviceMode">Jasa</button></div><form id="sellForm" class="seller-form"><div class="form-section"><h3>Informasi utama</h3><div class="field"><label>Judul listing</label><input id="sellTitle" minlength="5" maxlength="120" required placeholder="Contoh: Meja belajar kayu kondisi bagus"></div><div class="field"><label>Kategori</label><select id="sellCategory" required></select></div><div class="field"><label>Deskripsi</label><textarea id="sellDescription" minlength="10" maxlength="5000" required placeholder="Jelaskan kondisi, spesifikasi, kekurangan, dan hal penting lainnya."></textarea></div></div><div id="goodsFields"></div><div id="serviceFields" class="hidden"></div><div class="form-section"><h3>Kontak & foto</h3><div class="field"><label>WhatsApp untuk listing ini</label><input id="sellWhatsapp" type="tel" minlength="8" maxlength="20" required placeholder="08xxxxxxxxxx"></div><div class="field"><label>Foto listing</label><input id="sellPhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple><small class="muted" id="photoHelp">Barang umum minimal 3 foto. Maksimal 6 foto, 5 MB/foto.</small></div><div id="photoPreview" class="photo-preview"></div></div><div id="sellError" class="form-message error"></div><button class="btn primary full" id="submitListing">Kirim untuk review</button></form></section>'}
function goodsFields(){return '<div class="form-section"><h3>Detail barang</h3><div class="two-col"><div class="field"><label>Harga (Rp)</label><input id="sellPrice" type="number" min="0" required placeholder="150000"></div><div class="field"><label>Kondisi</label><select id="sellCondition" required><option value="bekas">Bekas</option><option value="baru">Baru</option></select></div></div><label class="check"><input id="sellNegotiable" type="checkbox"> Harga bisa dinegosiasikan</label><div class="field"><label>Lokasi COD</label><input id="sellLocation" minlength="2" maxlength="200" required placeholder="Padangsidimpuan Utara"></div><div id="motorFields"></div></div>'}
function serviceFields(){return '<div class="form-section"><h3>Detail jasa</h3><div class="field"><label>Harga / tarif</label><input id="servicePrice" maxlength="200" required placeholder="Mulai Rp50.000 / sesuai brief"></div><div class="field"><label>Estimasi waktu</label><input id="serviceTime" maxlength="200" required placeholder="1-3 hari"></div><div class="field"><label>Mode kerja</label><select id="serviceMode" required><option value="online">Online</option><option value="offline">Offline</option><option value="both">Online & Offline</option></select></div><div class="field"><label>Link contoh karya (opsional)</label><input id="serviceSample" maxlength="500" placeholder="https://..."></div></div>'}
async function loadCategories(type){const{data,error}=await sb.from("categories").select("id,name,slug,type").eq("type",type).eq("active",true).order("sort_order");return{data,error}}
async function prepareSeller(){document.getElementById("sellCategory").innerHTML='<option value="">Memuat...</option>';const{data}=await loadCategories(sellerMode);document.getElementById("sellCategory").innerHTML=(data||[]).map(c=>'<option value="'+c.id+'" data-slug="'+esc(c.slug)+'">'+esc(c.name)+'</option>').join("");document.getElementById("goodsFields").innerHTML=sellerMode==="barang"?goodsFields():"";document.getElementById("serviceFields").innerHTML=sellerMode==="jasa"?serviceFields():"";document.getElementById("serviceFields").classList.toggle("hidden",sellerMode!=="jasa");document.getElementById("goodsFields").classList.toggle("hidden",sellerMode!=="barang");bindMotorFields()}
function bindMotorFields(){const sel=document.getElementById("sellCategory");if(!sel)return;const check=()=>{const slug=sel.selectedOptions[0]?.dataset.slug||"";document.getElementById("motorFields").innerHTML=slug==="motor"?'<div class="motor-box"><div class="two-col"><div class="field"><label>Tahun</label><input id="motorYear" type="number" min="1900" max="2100" required></div><div class="field"><label>Kilometer</label><input id="motorMileage" type="number" min="0" placeholder="25000"></div></div><div class="two-col"><div class="field"><label>Pajak</label><select id="motorTax"><option value="hidup">Hidup</option><option value="mati">Mati</option><option value="tidak_tahu">Tidak tahu</option></select></div><div class="field"><label>Kelengkapan dokumen</label><select id="motorDocs"><option value="lengkap">Lengkap</option><option value="sebagian">Sebagian</option><option value="tidak_lengkap">Tidak lengkap</option></select></div></div></div>':""};sel.addEventListener("change",check);check()}
function bindSell(){sellerMode="barang";document.getElementById("goodsMode").onclick=()=>{sellerMode="barang";document.getElementById("goodsMode").classList.add("active");document.getElementById("serviceMode").classList.remove("active");prepareSeller()};document.getElementById("serviceMode").onclick=()=>{sellerMode="jasa";document.getElementById("serviceMode").classList.add("active");document.getElementById("goodsMode").classList.remove("active");prepareSeller()};document.getElementById("sellPhotos").addEventListener("change",previewPhotos);document.getElementById("sellForm").addEventListener("submit",submitListing);prepareSeller().then(()=>editingListingId?loadRejectedListing(editingListingId):loadProfileWhatsapp())}
async function loadProfileWhatsapp(){const{data}=await sb.from("profiles").select("whatsapp").eq("id",currentUser.id).maybeSingle();if(data?.whatsapp)document.getElementById("sellWhatsapp").value=data.whatsapp}
function previewPhotos(e){const files=[...e.target.files];const box=document.getElementById("photoPreview");box.innerHTML=files.slice(0,6).map(f=>'<div class="photo-item"><img src="'+URL.createObjectURL(f)+'" alt=""></div>').join("")}
/* submitListing: simpan listing, detail, dan foto. Jika gagal, data sementara dibersihkan. */
async function submitListing(e){e.preventDefault();const error=document.getElementById("sellError"),btn=document.getElementById("submitListing");error.textContent="";const files=[...document.getElementById("sellPhotos").files];const motorSlug=document.getElementById("sellCategory").selectedOptions[0]?.dataset.slug||"";const minPhotos=sellerMode==="jasa"?1:(motorSlug==="motor"?4:3);if(!editingListingId&&files.length<minPhotos){error.textContent=sellerMode==="jasa"?"Jasa membutuhkan minimal 1 foto.":motorSlug==="motor"?"Motor membutuhkan minimal 4 foto.":"Barang membutuhkan minimal 3 foto.";return}if(files.length>6||(editingListingId&&editingExistingPhotos.length+files.length>6)){error.textContent=editingListingId?"Maksimal 6 foto total.":"Maksimal 6 foto.";return}btn.disabled=true;btn.textContent=editingListingId?"Mengajukan ulang...":"Mengirim...";let id=editingListingId,uploadedPaths=[];try{const categoryId=Number(document.getElementById("sellCategory").value),contact=document.getElementById("sellWhatsapp").value.trim(),payload={category_id:categoryId,type:sellerMode,title:document.getElementById("sellTitle").value.trim(),description:document.getElementById("sellDescription").value.trim(),contact_whatsapp:contact,status:"pending",rejection_reason:null,approved_at:null,approved_by:null};if(editingListingId){
const rpcPayload={p_listing_id:editingListingId,p_category_id:categoryId,p_type:sellerMode,p_title:document.getElementById("sellTitle").value.trim(),p_description:document.getElementById("sellDescription").value.trim(),p_contact_whatsapp:contact,p_price:sellerMode==="barang"?Number(document.getElementById("sellPrice").value):null,p_negotiable:sellerMode==="barang"?document.getElementById("sellNegotiable").checked:null,p_condition:sellerMode==="barang"?document.getElementById("sellCondition").value:null,p_cod_location:sellerMode==="barang"?document.getElementById("sellLocation").value.trim():null,p_service_price_text:sellerMode==="jasa"?document.getElementById("servicePrice").value.trim():null,p_estimated_time:sellerMode==="jasa"?document.getElementById("serviceTime").value.trim():null,p_work_mode:sellerMode==="jasa"?document.getElementById("serviceMode").value:null,p_work_sample:sellerMode==="jasa"?document.getElementById("serviceSample").value.trim()||null:null,p_motor_year:null,p_motor_mileage:null,p_motor_tax_status:null,p_motor_document_completeness:null};
const slug=document.getElementById("sellCategory").selectedOptions[0]?.dataset.slug||"";
if(sellerMode==="barang"&&slug==="motor"){rpcPayload.p_motor_year=Number(document.getElementById("motorYear").value);rpcPayload.p_motor_mileage=document.getElementById("motorMileage").value?Number(document.getElementById("motorMileage").value):null;rpcPayload.p_motor_tax_status=document.getElementById("motorTax").value;rpcPayload.p_motor_document_completeness=document.getElementById("motorDocs").value}
for(let i=0;i<files.length;i++){const file=files[i];if(file.size>5*1024*1024)throw new Error("Foto melebihi batas 5 MB: "+file.name);const path=currentUser.id+"/"+editingListingId+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const{error:up}=await sb.storage.from("listing-images").upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;uploadedPaths.push(path);const{error:im}=await sb.from("listing_images").insert({listing_id:editingListingId,storage_path:path,sort_order:editingExistingPhotos.length+i});if(im)throw im}
const{error:rpcError}=await sb.rpc("resubmit_rejected_listing",rpcPayload);if(rpcError)throw rpcError;
toastMsg("Listing diperbaiki dan masuk review admin.");editingListingId=null;editingExistingPhotos=[];location.hash="#account";return}
const{data:listing,error:e1}=await sb.from("listings").insert({seller_id:currentUser.id,category_id:categoryId,type:sellerMode,title:document.getElementById("sellTitle").value.trim(),description:document.getElementById("sellDescription").value.trim(),contact_whatsapp:contact,status:"pending"}).select("id").single();if(e1)throw e1;id=listing.id;if(sellerMode==="barang"){const{error:e2}=await sb.from("item_details").insert({listing_id:id,price:Number(document.getElementById("sellPrice").value),negotiable:document.getElementById("sellNegotiable").checked,condition:document.getElementById("sellCondition").value,cod_location:document.getElementById("sellLocation").value.trim()});if(e2)throw e2;const slug=document.getElementById("sellCategory").selectedOptions[0]?.dataset.slug;if(slug==="motor"){const{error:e3}=await sb.from("motorbike_details").insert({listing_id:id,year:Number(document.getElementById("motorYear").value),mileage:document.getElementById("motorMileage").value?Number(document.getElementById("motorMileage").value):null,tax_status:document.getElementById("motorTax").value,document_completeness:document.getElementById("motorDocs").value});if(e3)throw e3}}else{const{error:e2}=await sb.from("service_details").insert({listing_id:id,price_text:document.getElementById("servicePrice").value.trim(),estimated_time:document.getElementById("serviceTime").value.trim(),work_mode:document.getElementById("serviceMode").value,work_sample:document.getElementById("serviceSample").value.trim()||null});if(e2)throw e2}for(let i=0;i<files.length;i++){const file=files[i];if(file.size>5*1024*1024)throw new Error("Foto melebihi batas 5 MB: "+file.name);const path=currentUser.id+"/"+id+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const{error:up}=await sb.storage.from("listing-images").upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;uploadedPaths.push(path);const{error:im}=await sb.from("listing_images").insert({listing_id:id,storage_path:path,sort_order:i});if(im)throw im}toastMsg("Listing masuk review admin.");location.hash="#account"}catch(x){if(uploadedPaths.length){await sb.from("listing_images").delete().in("storage_path",uploadedPaths);await sb.storage.from("listing-images").remove(uploadedPaths)}if(!editingListingId&&id){await sb.from("listing_images").delete().eq("listing_id",id);await sb.from("listings").delete().eq("id",id)}error.textContent=x.message||"Gagal menyimpan listing."}finally{btn.disabled=false;btn.textContent=editingListingId?"Ajukan ulang untuk review":"Kirim untuk review"}}
/* getListings: katalog publik hanya membaca listing berstatus published. */
async function getListings(f){let q=sb.from("listings").select("id,seller_id,title,description,type,status,contact_whatsapp,created_at,sold_at,item_details(price,condition,cod_location),service_details(price_text,work_mode),listing_images(storage_path,sort_order),categories!inner(name,slug)").eq("status","published");if(f.type)q=q.eq("type",f.type);if(f.category){q=q.eq("categories.slug",f.category)}if(f.q){const s=f.q.replace(/[,%().]/g," ").replace(/\s+/g," ").trim().slice(0,80);if(s)q=q.or("title.ilike.%"+s+"%,description.ilike.%"+s+"%")}if(f.sort==="oldest")q=q.order("created_at",{ascending:true}).order("id",{ascending:true});else q=q.order("created_at",{ascending:false}).order("id",{ascending:false});const page=Number.isInteger(f.page)?f.page:0;const from=page*12,to=from+11;return q.range(from,to)}
async function signedUrl(path){if(!path)return null;const{data,error}=await sb.storage.from("listing-images").createSignedUrl(path,3600);return error?null:data?.signedUrl}
async function card(x){const d=x.type==="barang"?x.item_details?.[0]:x.service_details?.[0],im=(x.listing_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0],url=await signedUrl(im?.storage_path),p=x.type==="barang"?(d?.price!=null?money(d.price):"Harga belum diisi"):(d?.price_text||"Harga sesuai layanan");return '<article class="listing-card" data-id="'+x.id+'"><div class="listing-media">'+(url?'<img src="'+esc(url)+'" alt="'+esc(x.title)+'" loading="lazy">':"<span>Foto belum tersedia</span>")+'</div><div class="listing-body"><div class="listing-title">'+esc(x.title)+'</div><div class="price">'+esc(p)+'</div><div class="meta">'+esc(x.categories?.name||"Lainnya")+' · '+esc(d?.condition||"Jasa")+'</div><div class="meta">📍 '+esc(d?.cod_location||"Padangsidimpuan")+'</div></div></article>'}
async function render(id,f){const el=document.getElementById(id);if(!el||browseLoading)return;browseLoading=true;if(f.page===0)el.innerHTML=skeletons(id==="homeListings"?4:6);const{data,error}=await getListings(f);browseLoading=false;if(error){if(f.page===0)el.innerHTML='<div class="error-box">Gagal memuat listing.</div>';return}const rows=data||[];if(f.page===0)currentListings=rows;else currentListings=[...currentListings,...rows];browseHasMore=rows.length===12;if(f.page===0&&!rows.length){el.innerHTML='<div class="empty">Belum ada listing aktif.</div>'}else{if(f.page===0)el.innerHTML="";const cards=await Promise.all(rows.map(card));el.insertAdjacentHTML("beforeend",cards.join(""));el.querySelectorAll("[data-id]").forEach(c=>c.onclick=()=>detail(c.dataset.id))}const more=document.getElementById("browseMore");if(more){more.innerHTML=browseHasMore?'<button class="btn secondary full" id="browseLoadMore">Muat lebih banyak</button>':"";document.getElementById("browseLoadMore")?.addEventListener("click",()=>{browsePage++;loadBrowse(true)})}}
/* detail: menampilkan detail listing dan kontak WhatsApp. */
async function getSellerName(id){if(!id)return"Penjual";const{data}=await sb.from("seller_public_profiles").select("name").eq("id",id).maybeSingle();return data?.name||"Penjual"}
async function detail(id){const x=currentListings.find(v=>v.id===id);if(!x)return;const d=x.type==="barang"?x.item_details?.[0]:x.service_details?.[0],im=(x.listing_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0],url=await signedUrl(im?.storage_path),sellerName=await getSellerName(x.seller_id),n=(x.contact_whatsapp||"").replace(/\D/g,"").replace(/^0/,"62"),fav=currentUser?await sb.from("favorites").select("listing_id").eq("user_id",currentUser.id).eq("listing_id",id).maybeSingle():{data:null};document.getElementById("listingDetail").innerHTML='<p class="eyebrow">'+esc(x.categories?.name||"Listing")+'</p><div class="detail-media">'+(url?'<img src="'+esc(url)+'" alt="'+esc(x.title)+'">':"Foto belum tersedia")+'</div><div class="detail-head"><div><h2>'+esc(x.title)+'</h2><div class="detail-price">'+esc(x.type==="barang"?(d?.price!=null?money(d.price):"Harga belum diisi"):(d?.price_text||"Harga sesuai layanan"))+'</div></div><button class="favorite-btn" id="favoriteBtn">'+(fav.data?"♥":"♡")+'</button></div><p class="muted">📍 '+esc(d?.cod_location||"Padangsidimpuan")+'</p><div class="detail-section"><strong>Deskripsi</strong><p>'+esc(x.description||"Belum ada deskripsi.")+'</p></div><div class="detail-section"><strong>Penjual</strong><div class="seller-box">'+esc(sellerName)+'</div></div><button class="btn secondary full" id="reportListingBtn">⚑ Laporkan listing</button><div class="detail-section trust"><strong>Tips aman</strong><p>Periksa barang sebelum membayar. Jangan berikan OTP atau data sensitif.</p></div>'+(n?'<a class="btn primary full sticky-cta" target="_blank" rel="noopener" href="https://wa.me/'+n+'?text='+encodeURIComponent("Halo, saya melihat listing \""+x.title+"\" di Lapak Sidimpuan.")+'">💬 Hubungi via WhatsApp</a>':"");listingModal.classList.remove("hidden");document.getElementById("favoriteBtn").onclick=()=>toggleFavorite(id,!!fav.data);document.getElementById("reportListingBtn").onclick=()=>reportListing(id,x.title)}
async function reportListing(id,title){if(!currentUser){openAuth("login");return}const reason=prompt("Alasan laporan:\n1. Penipuan / mencurigakan\n2. Informasi palsu\n3. Spam / iklan tidak relevan\n4. Konten terlarang\n5. Lainnya\n\nKetik nomor atau alasan singkat:","1");if(!reason)return;const map={"1":"penipuan","2":"informasi_palsu","3":"spam","4":"konten_terlarang","5":"lainnya"};const key=reason.trim().toLowerCase();const finalReason=map[key]||key.slice(0,100);const description=prompt("Tambahkan penjelasan (opsional):","");const{error}=await sb.from("reports").insert({reporter_id:currentUser.id,listing_id:id,reason:finalReason,description:description?description.slice(0,1000):null});if(error){toastMsg(error.code==="23505"?"Kamu sudah melaporkan listing ini.":error.message||"Laporan gagal dikirim.");return}toastMsg("Laporan berhasil dikirim ke admin.");listingModal.classList.add("hidden")}
async function toggleFavorite(id,active){if(!currentUser){closeAuth();openAuth();return}if(active){await sb.from("favorites").delete().eq("user_id",currentUser.id).eq("listing_id",id);toastMsg("Dihapus dari favorit.")}else{await sb.from("favorites").insert({user_id:currentUser.id,listing_id:id});toastMsg("Ditambahkan ke favorit.")}listingModal.classList.add("hidden")}
async function loadRejectedListing(id){const{data,error}=await sb.from("listings").select("id,title,description,type,category_id,contact_whatsapp,rejection_reason,item_details(price,negotiable,condition,cod_location),service_details(price_text,estimated_time,work_mode,work_sample),motorbike_details(year,mileage,tax_status,document_completeness),listing_images(storage_path,sort_order)").eq("id",id).eq("seller_id",currentUser.id).eq("status","rejected").maybeSingle();if(error||!data){document.getElementById("sellError").textContent="Listing ditolak tidak ditemukan atau sudah berubah.";return}editingExistingPhotos=(data.listing_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));sellerMode=data.type;document.getElementById("goodsMode").classList.toggle("active",sellerMode==="barang");document.getElementById("serviceMode").classList.toggle("active",sellerMode==="jasa");document.getElementById("sellTitle").value=data.title||"";document.getElementById("sellDescription").value=data.description||"";document.getElementById("sellWhatsapp").value=data.contact_whatsapp||"";document.getElementById("sellCategory").value=data.category_id;document.getElementById("sellCategory").dispatchEvent(new Event("change"));setTimeout(()=>{const d=data.item_details?.[0],s=data.service_details?.[0],m=data.motorbike_details?.[0];if(sellerMode==="barang"&&d){document.getElementById("sellPrice").value=d.price??"";document.getElementById("sellNegotiable").checked=!!d.negotiable;document.getElementById("sellCondition").value=d.condition||"bekas";document.getElementById("sellLocation").value=d.cod_location||"";if(m){document.getElementById("motorYear").value=m.year??"";document.getElementById("motorMileage").value=m.mileage??"";document.getElementById("motorTax").value=m.tax_status||"hidup";document.getElementById("motorDocs").value=m.document_completeness||"lengkap"}}else if(sellerMode==="jasa"&&s){document.getElementById("servicePrice").value=s.price_text||"";document.getElementById("serviceTime").value=s.estimated_time||"";document.getElementById("serviceMode").value=s.work_mode||"online";document.getElementById("serviceSample").value=s.work_sample||""}},0);document.getElementById("submitListing").textContent="Ajukan ulang untuk review";document.getElementById("photoHelp").textContent="Foto lama tetap dipakai. Kamu bisa menambahkan foto baru jika perlu (maksimal 6 total).";document.getElementById("sellError").innerHTML=data.rejection_reason?'<strong>Alasan ditolak:</strong> '+esc(data.rejection_reason):""}
async function sellerListings(){const{data,error}=await sb.from("listings").select("id,title,type,status,rejection_reason,created_at,sold_at,categories(name),item_details(price)").eq("seller_id",currentUser.id).order("created_at",{ascending:false});if(error)return '<div class="error-box">'+esc(error.message)+'</div>';if(!data?.length)return '<div class="empty"><h2>Belum ada listing</h2><p>Mulai dengan menjual barang atau jasa.</p><a class="btn primary" href="#sell">＋ Buat listing</a></div>';return '<div class="seller-list">'+data.map(x=>'<div class="seller-row"><div><strong>'+esc(x.title)+'</strong><span>'+esc(x.categories?.name||"")+' · '+esc(x.status==="sold"?"Terjual":x.status)+'</span></div><span class="status status-'+esc(x.status)+'">'+esc(x.status==="published"?"Aktif":x.status==="sold"?"Terjual":x.status==="pending"?"Review":"Arsip")+'</span>'+(x.status==="published"?'<button class="mini-btn" data-sold="'+x.id+'">Tandai terjual</button>':x.status==="rejected"?'<div class="listing-actions"><small class="muted">'+esc(x.rejection_reason||"Perlu diperbaiki sebelum diajukan ulang.")+'</small><button class="mini-btn" data-edit-rejected="'+x.id+'">Perbaiki</button></div>':"")+'</div>').join("")+'</div>'}
async function loadAccountContent(tab="listings"){const box=document.getElementById("accountContent");if(!box)return;box.innerHTML=skeletons(2);if(tab==="support"){return loadMySupport(box)}if(tab==="listings"){box.innerHTML=await sellerListings();box.querySelectorAll("[data-sold]").forEach(b=>b.onclick=()=>markSold(b.dataset.sold));box.querySelectorAll("[data-edit-rejected]").forEach(b=>b.onclick=()=>{editingListingId=b.dataset.editRejected;location.hash="#sell-edit/"+b.dataset.editRejected})}else{const{data}=await sb.from("favorites").select("listing_id,listings(id,seller_id,title,type,status,created_at,item_details(price,condition,cod_location),service_details(price_text,work_mode),listing_images(storage_path,sort_order),categories!inner(name,slug))").eq("user_id",currentUser.id);const rows=(data||[]).map(x=>x.listings).filter(Boolean);currentListings=rows;box.innerHTML=rows.length?(await Promise.all(rows.map(card))).join(""):'<div class="empty">Belum ada favorit.</div>';box.querySelectorAll("[data-id]").forEach(c=>c.onclick=()=>detail(c.dataset.id))}}
async function loadMySupport(box){const{data,error}=await sb.from("support_tickets").select("id,category,subject,message,status,admin_reply,created_at,updated_at").order("updated_at",{ascending:false}).limit(30);if(error){box.innerHTML='<div class="error-box">'+esc(error.message)+'</div>';return}box.innerHTML=(data||[]).length?'<div class="support-list">'+data.map(t=>'<article class="support-card"><div class="support-head"><strong>'+esc(t.subject)+'</strong><span class="status status-'+esc(t.status)+'">'+esc(t.status)+'</span></div><small>'+esc(t.category)+' · '+esc(new Date(t.created_at).toLocaleString("id-ID"))+'</small><p>'+esc(t.message)+'</p>'+(t.admin_reply?'<div class="support-reply"><strong>Balasan admin</strong><p>'+esc(t.admin_reply)+'</p></div>':'<p class="muted">Belum ada balasan admin.</p>')+'</article>').join("")+'</div>':'<div class="empty"><h2>Belum ada tiket bantuan.</h2><p>Kalau ada masalah, gunakan tombol Hubungi Admin.</p></div>'}
function openSupport(){if(!currentUser){openAuth();return}document.getElementById("supportModal").classList.remove("hidden")}
function closeSupport(){document.getElementById("supportModal").classList.add("hidden")}
async function submitSupport(e){e.preventDefault();const msg=document.getElementById("supportFormMessage"),btn=e.target.querySelector("button[type=submit]");msg.textContent="Mengirim...";msg.className="form-message";btn.disabled=true;const{data,error}=await sb.from("support_tickets").insert({user_id:currentUser.id,category:document.getElementById("supportCategory").value,subject:document.getElementById("supportSubject").value.trim(),message:document.getElementById("supportMessage").value.trim()}).select("id").single();if(error){msg.textContent=error.message;msg.className="form-message error";btn.disabled=false;return}msg.textContent="Tiket #"+data.id.slice(0,8)+" sudah dikirim ke admin.";msg.className="form-message success";e.target.reset();btn.disabled=false;setTimeout(()=>{closeSupport();location.hash="#account"},900)}
async function markSold(id){if(!confirm("Tandai listing ini sebagai terjual? Listing akan hilang dari katalog publik."))return;const{error}=await sb.from("listings").update({status:"sold",sold_at:new Date().toISOString()}).eq("id",id).eq("seller_id",currentUser.id).eq("status","published");if(error){toastMsg(error.message);return}toastMsg("Listing ditandai terjual.");loadAccountContent("listings")}
function nav(r){document.querySelectorAll("[data-nav]").forEach(a=>a.classList.toggle("active",a.dataset.nav===r))}
/* route: memilih halaman berdasarkan hash URL seperti #home atau #browse. */
function route(){const r=(location.hash.replace(/^#/,"")||"home").split("/")[0];if(r==="home"){app.innerHTML=home();nav("home");render("homeListings",{});bindHome()}else if(r==="browse"){app.innerHTML=browse();nav("browse");bindBrowse();loadBrowse()}else if(r==="account"){app.innerHTML=account();nav("account");bindAccount()}else if(r==="favorites"){app.innerHTML=favorites();nav("favorites");loadFavoritePage()}else if(r==="sell"){editingListingId=null;editingExistingPhotos=[];app.innerHTML=sell();nav("");bindSell()}else if(r==="sell-edit"){if(!currentUser){openAuth();return}editingListingId=location.hash.split("/")[1]||null;app.innerHTML=sell();nav("");bindSell()}else location.hash="#home"}
function bindHome(){document.getElementById("homeSearch")?.addEventListener("submit",e=>{e.preventDefault();const q=document.getElementById("homeQuery").value.trim();location.hash="#browse";setTimeout(()=>{const i=document.getElementById("browseQuery");if(i){i.value=q;document.getElementById("browseSearch").dispatchEvent(new Event("submit"))}},0)});document.querySelectorAll("[data-category]").forEach(b=>b.addEventListener("click",()=>{currentFilter=b.dataset.category;location.hash="#browse"}));document.getElementById("heroSell")?.addEventListener("click",()=>location.hash="#sell")}
function loadBrowse(append=false){const q=document.getElementById("browseQuery")?.value.trim()||"",sort=document.getElementById("browseSort")?.value||"newest";if(!append)browsePage=0;const f=currentFilter;render("browseListings",{type:["barang","jasa"].includes(f)?f:null,category:["all","barang","jasa"].includes(f)?null:f,q,sort,page:browsePage})}
function bindBrowse(){document.getElementById("browseSearch")?.addEventListener("submit",e=>{e.preventDefault();loadBrowse()});document.getElementById("browseSort")?.addEventListener("change",()=>loadBrowse());document.querySelectorAll(".filter-chip").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter-chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;loadBrowse()}));const active=document.querySelector('.filter-chip[data-filter="'+currentFilter+'"]');if(active){document.querySelectorAll(".filter-chip").forEach(x=>x.classList.remove("active"));active.classList.add("active")}}
function bindAccount(){document.getElementById("accountLogin")?.addEventListener("click",()=>openAuth());document.getElementById("accountLogout")?.addEventListener("click",logout);document.getElementById("contactAdmin")?.addEventListener("click",openSupport);document.querySelectorAll("[data-account-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-account-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadAccountContent(b.dataset.accountTab)});loadAccountContent("listings")}
async function loadFavoritePage(){if(!currentUser){app.innerHTML='<section class="page"><div class="empty"><h2>Masuk untuk melihat favorit</h2><button class="btn primary" id="favLogin">Masuk</button></div></section>';document.getElementById("favLogin").onclick=()=>openAuth();return}const{data}=await sb.from("favorites").select("listing_id,listings(id,seller_id,title,type,status,created_at,item_details(price,condition,cod_location),service_details(price_text,work_mode),listing_images(storage_path,sort_order),categories!inner(name,slug))").eq("user_id",currentUser.id);const rows=(data||[]).map(x=>x.listings).filter(Boolean);currentListings=rows;const el=document.getElementById("favoriteListings");el.innerHTML=rows.length?(await Promise.all(rows.map(card))).join(""):'<div class="empty">Belum ada favorit.</div>';el.querySelectorAll("[data-id]").forEach(c=>c.onclick=()=>detail(c.dataset.id))}
document.getElementById("accountBtn").addEventListener("click",()=>currentUser?location.hash="#account":openAuth());document.getElementById("headerSearchBtn").addEventListener("click",()=>location.hash="#browse");document.getElementById("sellNav").addEventListener("click",()=>location.hash="#sell");document.getElementById("closeAuth").addEventListener("click",closeAuth);document.getElementById("closeListing").addEventListener("click",()=>listingModal.classList.add("hidden"));document.getElementById("closeSupport").addEventListener("click",closeSupport);document.getElementById("supportForm").addEventListener("submit",submitSupport);document.getElementById("supportModal").addEventListener("click",e=>{if(e.target===supportModal)closeSupport()});document.getElementById("loginTab").addEventListener("click",()=>setMode("login"));document.getElementById("registerTab").addEventListener("click",()=>setMode("register"));document.getElementById("authForm").addEventListener("submit",submitAuth);document.getElementById("authModal").addEventListener("click",e=>{if(e.target===authModal)closeAuth()});document.getElementById("listingModal").addEventListener("click",e=>{if(e.target===listingModal)listingModal.classList.add("hidden")});window.addEventListener("hashchange",route);sb.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;updateAccount()});setMode("login");route();loadUser().catch(()=>{currentUser=null;updateAccount()});
